### ISSUE TITLE
README should lead with URL to canonical LilyDev repository

### ISSUE THREAD

**Issue by MarkDBlackwell** [fedelibre/LilyDevDebian#5]
If people search on GitHub for 'LilyDev', (naturally) the results don't indicate whose repository is the canonical one.

In general (as you may know), GitHub's [Relative links in READMEs](https://help.github.com/articles/relative-links-in-readmes/) help page recommends against absolute links (such as `[Absolute link](https://github.com/username/repo/blob/branch/docs/more_words.md)` because in forks of your repository most such links won't work as intended.

However, if at the top of your README you simply place an absolute link (and many do so) to your own (canonical) LilyDev repository, then anyone who might happen upon a fork of it (such as mine, after I rebase) will be able to see easily that mine isn't the canonical one, but that yours is.

Right now, I suppose no problem exists, but later other people might jump in as well and help.

Per GitHub help section [URL autolinking](https://help.github.com/articles/github-flavored-markdown/#url-autolinking), I believe merely including the text `https://github.com/fedelibre/LilyDev` at the top of your README would best accomplish this.

**Comment by fedelibre** [comment]
I don't see your point. When you search a project in github, the forked repositories are not listed, unless you want to list them:

```
lilydev fork:true
```

There's an explanation [here](https://help.github.com/articles/searching-code/#search-by-the-number-of-forks-the-parent-repository-has).

If anybody lands on a forked repository instead of the original one, this is clearly stated in the header, which says "forked from...".

Finally, I don't see how placing the absolute URL of a project in the README may help. When you rebase your fork and push it, your fork README will be identical to this repository. Where did you read about this?

I'm closing this issue. If I missed anything feel free to reopen it.

**Comment by MarkDBlackwell** [comment]
> If anybody lands on a forked repository instead of the original one, this is clearly stated in the header, which says "forked from..."
> When you search a project in GitHub, the forked repositories are not listed

Of course, you're completely correct—now I see the issue is nonexistent!

> Where did you read about this?

I searched but couldn't find a reference for this. (Somehow, I remembered GitHub working differently in the past.)

> When you rebase your fork and push it, your fork's README will be identical to this repository

That's the whole idea. It distinguishes two classes of forks: in those created merely to assist you, the absolute URL in the unchanged README is another visual reminder still pointing (by default) to your canonical repository. This helps readers further to know this repository isn't the canonical one. In more venturesome (and distant) forks, the author naturally changes or removes this.

And even the canonical repository can display "forked from..." in the GitHub header if it was forked (in turn) from some more ancient ancestor. For example, [cbucher/console](https://github.com/cbucher/console/) displays "forked from..." in the GitHub header even though it's the canonical repository: currently it's alive and under development. It was forked from [bozho/console](https://github.com/bozho/console) which isn't the canonical repository since it's dead.
